install.packages("haven")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("NbClust")
install.packages("plotly")
install.packages("C50")
install.packages("rpart")
install.packages("tidyverse")
install.packages(c("neuralnet", "keras", "tensorflow"), dependencies = TRUE)
